[project]
name = "streamlit-garden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "streamlit-image-comparison>=0.0.4",
    "streamlit>=1.49.1",
]
